name: monkey-go-lint

on:
  push:
    paths:
      - go
    branches: 
      - main
  pull_request:
    paths:
      - go
    branches:
      - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Intall Go
        uses: actions/setup-go@v2
        with:
          stable: 'false'
          go-version: '1.21.0'
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Install golangci-lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.55.2
      - name: lint
        run: |
          cd go
          golangci-lint run
