name: monkey-go-test

on:
  push:
    branches: 
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: test
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.platform }}
    
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.21.x
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: test
        run: |
          cd go
          go test ./...
